
environment_config:
  path: business/util/config/env.dart
  fields:
    env:
      default: 'dev'
      type: String

    baseUrl:
      default: "${env =='dev'
      ? 'http://192.168.1.11/komix.serkancelik.web.tr/public'
      : 'https://komix.serkancelik.web.tr'}"
      type: String

    apiUrl:
      default: "$baseUrl/api/v1"
      type: String

    imageAssetsUrl:
      default: "$baseUrl/assets/images"
      type: String

    pagePictureLimit:
      default: "(env == 'prod') ? 20 :5"
      type: int

    isCached:
       default: true
       type: bool