
environment_config:
  path: business/config/env.dart
  fields:
    env:
      default: 'dev'

    baseUrl:
      default: "${env =='dev'
      ? 'http://192.168.1.20/komikseyler.serkancelik.web.tr/public'
      : 'https://komikseyler.serkancelik.web.tr'}"

    imageAssetsUrl:
      default: "$baseUrl/assets/images"

    pagePictureLimit:
      default: "(env == 'prod') ? 20 :5"
      type: int